name: opencart

services:
  apache:
    container_name: opencart-apache
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/public_html
    depends_on:
      php:
        condition: service_healthy
    networks:
      - opencart

  php:
    container_name: opencart-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - PHP_VERSION=8.4
    volumes:
      - .:/var/www/public_html
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t || exit 1"]
      interval: 2s
      timeout: 1s
      retries: 3
    networks:
      - opencart

  mysql:
    container_name: opencart-mysql
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-opencart}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-opencart}
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-opencart}"]
      interval: 2s
      timeout: 2s
      retries: 3
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - opencart

  adminer:
    container_name: opencart-adminer
    image: adminer:latest
    profiles: [adminer]
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - opencart

  redis:
    container_name: opencart-redis
    image: redis:latest
    profiles: [redis]
    volumes:
      - redis-data:/data
    networks:
      - opencart

  memcached:
    container_name: opencart-memcached
    image: memcached:latest
    profiles: [memcached]
    networks:
      - opencart

  postgres:
    container_name: opencart-postgres
    image: postgres:latest
    profiles: [postgres]
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-opencart}
      - POSTGRES_DB=${POSTGRES_DB:-opencart}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - opencart

volumes:
    mysql-data:
    postgres-data:
    redis-data:

networks:
  opencart:
    driver: bridge
    name: opencart-network
