services:
  opencart:
    build:
      context: ./docker/php
      args:
        - PHP_VERSION=8.4
    user: 1000:1000
    ports:
      - "80:80"
    volumes:
      - ./upload:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-opencart}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-opencart}
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-opencart}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    volumes:
        - redis-data:/data

  memcached:
    image: memcached:latest

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-opencart}
      - POSTGRES_DB=${POSTGRES_DB:-opencart}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
    mysql-data:
    postgres-data:
    redis-data:
